### ISSUE TITLE
Docker-compose?

### ISSUE THREAD

**Issue by BadCo-NZ** [cglatot/pasta#57]
Is anyone able to share there docker compose file, or even the docker run command?

Thanks!

**Comment by cglatot** [comment]
https://github.com/cglatot/pasta/issues/41#issuecomment-931369775

**Comment by BadCo-NZ** [comment]
> [#41 (comment)](https://github.com/cglatot/pasta/issues/41#issuecomment-931369775)

Thanks, I did find that one but it is incomplete.

**Comment by BadCo-NZ** [comment]
Here is my example for future searchers

```
version: "3"

services:
  app:
    image: cglatot/pasta
    container_name: pasta
    ports:
      - 8087:80 
    restart: unless-stopped
```

@cglatot would you accept a PR with an example docker-compose file?
